name: "Devialet Controller"
description: "Control Devialet speaker via API"
version: "1.0.0"
slug: "devialet_controller"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000

#ToRemove
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int